SLICE_OUTPUT_STR_METHOD = 20

INGREDIENTS_NAME_MAX_LENGTH_CHARFIELD = 128

INGREDIENTS_MEASUREMENT_UNIT_MAX_LENGTH_CHARFIELD = 64

TAG_NAME_MAX_LENGTH_CHARFIELD = 32

TAG_SLUG_MAX_LENGTH_SLUGFIELD = 32

RECIPE_NAME_MAX_LENGTH_CHARFIELD = 256

RECIPE_MIN_COOKING_TIME = 1

RECIPE_INGREDIENT_MIN_AMOUNT = 1

USER_MAX_LENGTH_CHARFIELD = 150

USER_MAX_LENGTH_EMAILFIELD = 254
