TAG_NAME_MAX_LENGTH_CHARFIELD = 32

TAG_SLUG_MAX_LENGTH_SLUGFIELD = 32

RECIPE_NAME_MAX_LENGTH_CHARFIELD = 256

RECIPE_MIN_COOKING_TIME = 1

RECIPE_MAX_COOKING_TIME = 480

RECIPE_INGREDIENT_MIN_AMOUNT = 1

RECIPE_SHORT_LINK_MAX_LENGTH_CHARFIELD = 100
