# Generated by Django 5.1.1 on 2026-04-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
